mentors/urls.py
from django.urls import path, include
from  . import views
from mentors.views import *


urlpatterns = [
    #gestion site
    path('', views.home, name='home'),
    path('login', views.Login, name='login'),
    path('user_profile', views.user_profile, name='user_profile'),
    path('editprofile/<int:id>', views.editprofile, name='editprofile'),
    path('createuser', views.createuser, name='createuser'),
    path('login_user', views.login_user, name='login_user'),
    path('logout_user', views.logout_user, name='logout_user'),
    path('about', views.about, name='about'),
    path('Mentors', views.Mentors, name='Mentors'),
    path('abonnement/<int:id>', views.abonnement, name='abonnement'),
    path('desabonnement/', views.desabonnement, name='desabonnement'),
    path('orientation', views.tableau_orientations, name='orientation'),
    path('get_all_even', views.get_all_even, name='get_all_even'),
    path('get_all_ressource', views.get_all_ressource, name='get_all_ressource'),
    path('add_even', views.add_even, name='add_even'),
    path('add_ressource', views.add_ressource, name='add_ressource'),
    path('get_all_forum', views.get_all_forum, name='get_all_forum'),
    path('add_forum', views.add_forum, name='add_forum'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from  django.conf.urls.static import  static
from  django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('mentors.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mentors/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.db.models.signals import post_save
from django.dispatch import receiver
import mimetypes


class Regions(models.Model):
    numero = models.CharField(max_length=1000, blank=True, null=True, verbose_name="Numero d'ordre")
    nomreg = models.CharField(max_length=1000, blank=True, null=True, verbose_name="Nom de la region")
    cheflieu = models.CharField(max_length=1000, blank=True, null=True, verbose_name="Chef lieu")
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    
    class Meta:
        verbose_name = "Regions"
        verbose_name_plural = "Region"
        
    def __str__(self):
        return self.nomreg




class Provinces(models.Model):
    numero = models.CharField(max_length=1000, blank=True, null=True,verbose_name="Numero d'ordre")
    nomprov = models.CharField(max_length=500, blank=True, null=True, verbose_name="Nom de la province")
    region = models.ForeignKey(Regions, blank=True, null=True, on_delete=models.CASCADE, verbose_name="Region")
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)

    
    class Meta:
        verbose_name = "Provinces"
        verbose_name_plural = "Province"
        
    def __str__(self):
        return self.nomprov
    



class Communes(models.Model):
    nom_commune = models.CharField(max_length=1000, blank=True, null=True, verbose_name="Nom de la commune")
    province = models.ForeignKey(Provinces, blank=True, null=True, on_delete=models.CASCADE,verbose_name="Province")
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    
    def __str__(self):
        return self.nom_commune
    
class Status(models.Model):
    statut = models.CharField(max_length=100, blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)

    def __str__(self):
        return self.statut

class Etablissement(models.Model):
    libelle = models.CharField(max_length=20, blank=True, null=True)
    statut = models.ForeignKey(Status, blank=True, null=True, on_delete=models.CASCADE)
    commune = models.ForeignKey(Communes, blank=True, null=True, on_delete=models.CASCADE)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)

    def __str__(self):
        return self.libelle




class Ressources(models.Model):
    titre = models.CharField(max_length=50, null=True, blank=True)
    description = models.TextField(blank=True, null=True)
    ressource = models.FileField(upload_to='Fichiers/', null=True, blank=True)
    owner = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)

    
    def __str__(self):
        return self.titre
    
    
    def get_mime_type(self):
        if self.ressource:
            return mimetypes.guess_type(self.ressource.path)[0]
        else:
            return None
        
        
class Forum(models.Model):
    titre = models.CharField(max_length=50, null=True, blank=True)
    description = models.TextField(blank=True, null=True)
    fichier = models.FileField(upload_to='forum_img/', null=True, blank=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    
    IMAGE_MAX_SIZE = (370, 260)
    
    def resize_image(self):
        image = Image.open(self.image)
        image.thumbnail(self.IMAGE_MAX_SIZE)
        # sauvegarde de l’image redimensionnée dans le système de fichiers
        # ce n’est pas la méthode save() du modèle !
        image.save(self.image.path)
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.resize_image()
        
        
    def __str__(self):
        return self.titre
        
        
class ForumComment(models.Model):
    comment = models.TextField(blank=True, null=True)
    forum = models.ForeignKey(Forum, blank=True, null=True, on_delete=models.CASCADE)
    user_comment = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    

    def __str__(self):
        return self.comment 
    
    
class Badge(models.Model):
    classe_badge = models.CharField(max_length=100, blank=True, null=True)
    badge = models.FileField(upload_to='images/', null=True, blank=True)
    description = models.TextField(blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    
    IMAGE_MAX_SIZE = (70, 60)
    
    def resize_image(self):
        image = Image.open(self.badge)
        image.thumbnail(self.IMAGE_MAX_SIZE)
        image.save(self.badge.path)
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.resize_image()
        
    
    
    def __str__(self):
        return self.classe_badge
    
    
class CategorieFormation(models.Model):
    libelle = models.CharField(max_length=100, blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    
    def __str__(self):
        return self.libelle
    
class Domaine(models.Model):
    libelle = models.CharField(max_length=100, blank=True, null=True)
    categorie = models.ForeignKey(CategorieFormation, blank=True, null=True, on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    
    
    def __str__(self):
        return self.libelle





class Evenement(models.Model):
    libelle = models.CharField(max_length=100, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    lien = models.CharField(max_length=1000, blank=True, null=True)
    image = models.FileField(upload_to='images/', null=True, blank=True)
    date_even = models.DateField(blank=True, null=True)
    initiateur = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    
    
    def __str__(self):
        return self.libelle 
    
    
    IMAGE_MAX_SIZE = (370, 260)
    
    def resize_image(self):
        image = Image.open(self.image)
        image.thumbnail(self.IMAGE_MAX_SIZE)
        image.save(self.image.path)
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.resize_image()
        
        
        
        
class Type_oriention(models.Model):
    libelle = models.CharField(max_length=100, blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    
    def __str__(self):
        return self.libelle


class Filiere_Serie(models.Model):
    type = models.ForeignKey(Type_oriention, blank=True, null=True, on_delete=models.CASCADE)
    libelle = models.CharField(max_length=100, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    
    def __str__(self):
        return self.libelle
    
    
class Debouche(models.Model):
    debouche = models.ForeignKey(Filiere_Serie, blank=True, null=True, on_delete=models.CASCADE)
    libelle = models.TextField(blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    
    def __str__(self):
        return self.libelle
    
    
class Typementorat(models.Model):
    libelle = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    
    def __str__(self):
        return self.libelle
    
class Niveau_formation(models.Model):
    libelle = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    
    def __str__(self):
        return self.libelle
  
    
class Profiles(models.Model):
    user = models.OneToOneField(User, blank=True, null=True, on_delete=models.CASCADE)

mentors/forms.py
# users/forms.py
from django import forms
from django.core.validators import RegexValidator
from django import forms
from .models import *
#from phonenumber_field.widgets import PhoneNumberInternationalFallbackWidget, PhoneNumberPrefixWidget


class LoginForm(forms.Form):
    username = forms.CharField(max_length=63, label='Nom tilisateur')
    password = forms.CharField(max_length=63, widget=forms.PasswordInput, label='Mot de passe')

mentors/templates/mentors/Mentors.html
{% extends "base.html" %}

{% load static %}
{% block main %}
  
 <a class="banner" href=""><img class="h-25" src="{% static 'media/images/dispositifs.png' %}" alt="" height="0"></a>
 <div class="row mx-3 mb-3">
  {% if not mentors_group %}
    <div class="col-sm-6 text-center">
      <div class="card">
        <div class="card-body">
          <a href="#" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Je veux être mentor</a>
        </div>
      </div>
    </div>
  {% endif %}
    
  {% if not user_group %}
    <div class="col-sm-6 text-center">
      <div class="card">
        <div class="card-body">
          <a href="#" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal1">Je trouve un mentor</a>
        </div>
      </div>
    </div>
  {% endif %}
</div>
 
{% if mentors_group or user_group %}
  <div class="container mb-3">
    <div class="py-6">
      <div class="row">
        {% for mentor in mentors_profiles %}
          <div class="col-lg-3 col-12">
            <!-- avatar -->
            <div class="avatar avatar-xl mt-n7 ms-4">
              {% if mentor.photo %}
                <img src="{{ mentor.photo.url }}" alt="Image" class="w-25 rounded-circle border-4 border-white-color-40">
              {% else %}
                <img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="Image" class="w-25 rounded-circle border-4 border-white-color-40">
              {% endif %}
            </div>
            <!-- card body -->
            <div class="card-body">
              <!-- Title -->
              <h6 class="mb-1">{{mentor.user.first_name}} &nbsp; {{mentor.user.last_name}}</h6>
              <div>
                <!-- Dropdown -->
                <div class="d-flex justify-content-between align-items-center">
                  <a href="{% url 'abonnement' mentor.id %}" class="btn btn-primary">S'abonner</a>
                  <div class="dropdown dropstart">
                    <a href="#!" class="btn btn-ghost btn-icon btn-sm rounded-circle" id="dropdownMenuOne" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-more-vertical icon-xs"><circle cx="12" cy="12" r="1"></circle><circle cx="12" cy="5" r="1"></circle><circle cx="12" cy="19" r="1"></circle></svg>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuOne">
                      <a class="dropdown-item d-flex align-items-center" href="{% url 'desabonnement' %}"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text me-2 icon-xxs dropdown-item-icon"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>Désabonné</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% if forloop.counter|divisibleby:4 %}
            </div>
            <div class="row">
          {% endif %}
        {% endfor %}
      </div>
    </div>
  </div>
{% endif %}

{% include "mentors/mentors_legal.html" %}
{% include "mentors/users_legal.html" %}

{% for message in messages %}
  <script src="{% static 'js/sweetalert.min.js' %}"></script>
  {% if message.tags == 'error' %}
    <script>
      var m = "{{ message }}";
      swal("Réfusé!", m, "error");
    </script>
  {% elif message.tags == 'success' %}
    <script>
      var m = "{{ message }}";
      swal("Bienvenue!", m, "success");
    </script>
  {% elif message.tags == 'warning' %}
    <script>
      var m = "{{ message }}";
      swal("A bientôt!", m, "warning");
    </script>
  {% endif %}
{% endfor %}

{% endblock main %}

mentors/templates/mentors/about.html
{% extends "base.html" %}

{% block main %}

<!-- My Approach-->
<section class="section section-lg bg-default">
    <div class="container">
        <div class="row row-50 justify-content-center justify-content-xl-between flex-lg-row-reverse">
            <div class="col-md-11 col-lg-6 col-xl-5">
                <div class="box-1">
                    <h5>PRÉSENTATION DE L’ASSOCIATION</h5>
                    <h5>1- Cible</h5>
                    <p>
                        L’association s'adresse aux élèves et étudiants en recherche d'orientation scolaire ou
                        professionnelle, aux adultes en reconversion , aux personnes sans emploi, ainsi qu'à toute
                        personne désireuse d'améliorer ses perspectives professionnelles.</p><button class="btn btn-primary" data-toggle="modal" data-target="#staticBackdrop">Lire plus</button>
                </div>
                {% include "mentors/about1.html" %}
            </div>
            <div class="col-md-11 col-lg-6">
                <!-- Thumbnail Media-->
                <div class="thumbnail-media" style="background-image: url(media/images/mentorat.svg);">
                    <a class="icon thumbnail-media-icon mdi mdi-play-circle-outline" href="//www.youtube.com/watch?v=I5FlP07kdvM" data-lightgallery="item"></a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Services-->
<section class="section section-lg bg-gray-100 text-center">
    <div class="container">
        <h2 class="wow fadeIn">DOMAINES DE FORMATIONS</h2>
        {% for data in categories %}
        <details class="plus-type outer-line" data-details-toggle="group-toggle">
            <summary class="display-block" id="summary_2_{{data.id}}">
                <button class="btn btn-secondary">{{ data.libelle }}</button>
            </summary>
            {% for domaine in data.domaine_set.all %}
            <div aria-describedby="summary_2_{{data.id}}" class="padding-top-half-gutter flex flex-top half-gutter no-fit no-margin-bottom justify-content-stretch" data-nosnippet>
                <div class="xs-hide s-4 l-3">
                    <div class="ratio-100">
                      <div class="row text-capitalize text-end"> <i class="fa fa-heart text-success"> &nbsp; &nbsp;{{ domaine.libelle }}</i></div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </details>
        {% endfor %}
    </div>
</section>

{% endblock main %}

mentors/templates/mentors/accordeon.html
<details class="plus-type outer-line" data-details-toggle="group-toggle">
    <summary class="display-block" id="summary_2_0">
      <span class="screen-readers">Texte fictif : </span>Lorem varius lorem
    </summary>
    <div aria-describedby="summary_2_0" class="padding-top-half-gutter flex flex-top half-gutter no-fit no-margin-bottom justify-content-stretch" data-nosnippet>
      <div class="xs-hide s-4 l-3">
        <div class="ratio-100">
          <picture class="dark-mode-hide">
            <img decoding="async" loading="lazy" src="https://pictures.kortic.com/200x200/000000.webp" alt="Image de remplacement 200x200" width="200" height="200">
          </picture>
          <picture class="dark-mode-show">
            <img decoding="async" loading="lazy" src="https://pictures.kortic.com/200x200/ffffff.webp" alt="Image de remplacement 200x200" width="200" height="200">
          </picture>
        </div>
      </div>
      <div>
      <span class="screen-readers">Texte fictif : </span><p>
  Vitae amet eu et ultricies tellus fermentum tincidunt ullamcorper diam cursus adipiscing euismod.
  </p>
  <p>
  Mi nec ultrices euismod semper non ligula duis pellentesque in lectus duis ipsum eu amet scelerisque est et.
  </p>
  <p>
  Odio justo fermentum eu curae in felis elit nec consequat pellentesque fusce lobortis purus erat volutpat.
  </p>
  <p>
  Aenean egestas poda cras at mi ipsum fusce suspendisse amet non imperdiet.
  </p>
  </div></div>
  </details>
  <details class="plus-type outer-line" data-details-toggle="group-toggle">
    <summary class="display-block" id="summary_2_1">
      <span class="screen-readers">Texte fictif : </span>Lorem non convallis iaculis fermentum
    </summary>
    <div aria-describedby="summary_2_1" class="padding-top-half-gutter flex flex-top half-gutter no-fit no-margin-bottom justify-content-stretch" data-nosnippet>
      <div class="xs-hide s-4 l-3">
        <div class="ratio-100">
          <picture class="dark-mode-hide">
            <img decoding="async" loading="lazy" src="https://pictures.kortic.com/200x200/000000.webp" alt="Image de remplacement 200x200" width="200" height="200">
          </picture>
          <picture class="dark-mode-show">
            <img decoding="async" loading="lazy" src="https://pictures.kortic.com/200x200/ffffff.webp" alt="Image de remplacement 200x200" width="200" height="200">
          </picture>
        </div>
      </div>
      <div>
      <span class="screen-readers">Texte fictif : </span><p>
  Enim cursus egestas nibh luctus ante vel et vehicula integer curae elit sapien purus elit justo mollis blandit pellentesque pretium ultricies fusce sodales tortor.
  </p>
  <p>
  Pellentesque ornare aliquet nulla sed nulla tincidunt nulla congue sapien morbi est sit amet risus sed pellentesque curabitur diam varius lorem convallis ullamcorper in sit nisl dignissim fermentum faucibus non semper tempus fermentum et.
  </p>
  <p>
  Tempus lorem egestas lorem iaculis massa faucibus vitae augue fermentum consectetur enim primis in ligula in dui sed ultrices sollicitudin praesent enim egestas.
  </p>
  </div></div>
  </details>
  <details class="plus-type outer-line" data-details-toggle="group-toggle" open>
    <summary class="display-block" id="summary_2_2">
      <span class="screen-readers">Texte fictif : </span>Lorem mauris dolor
    </summary>
    <div aria-describedby="summary_2_2" class="padding-top-half-gutter flex flex-top half-gutter no-fit no-margin-bottom justify-content-stretch" data-nosnippet>
      <div class="xs-hide s-4 l-3">
        <div class="ratio-100">
          <picture class="dark-mode-hide">
            <img decoding="async" loading="lazy" src="https://pictures.kortic.com/200x200/000000.webp" alt="Image de remplacement 200x200" width="200" height="200">
          </picture>
          <picture class="dark-mode-show">
            <img decoding="async" loading="lazy" src="https://pictures.kortic.com/200x200/ffffff.webp" alt="Image de remplacement 200x200" width="200" height="200">
          </picture>
        </div>
      </div>
      <div>
      <span class="screen-readers">Texte fictif : </span><p>
  Lorem at pretium poda cubilia sapien sit primis porttitor quis elementum suscipit lorem augue nunc.
  </p>
  <p>
  Nisl nulla augue erat blandit morbi risus varius enim ullamcorper non elementum in consectetuer sed ultricies sed amet elit faucibus.
  </p>
  </div></div>
  </details>
  <details class="plus-type outer-line" data-details-toggle="group-toggle">
    <summary class="display-block" id="summary_2_3">
      <span class="screen-readers">Texte fictif : </span>Lorem adipiscing ut proin
    </summary>
    <div aria-describedby="summary_2_3" class="padding-top-half-gutter flex flex-top half-gutter no-fit no-margin-bottom justify-content-stretch" data-nosnippet>
      <div class="xs-hide s-4 l-3">
        <div class="ratio-100">
          <picture class="dark-mode-hide">
            <img decoding="async" loading="lazy" src="https://pictures.kortic.com/200x200/000000.webp" alt="Image de remplacement 200x200" width="200" height="200">
          </picture>
          <picture class="dark-mode-show">
            <img decoding="async" loading="lazy" src="https://pictures.kortic.com/200x200/ffffff.webp" alt="Image de remplacement 200x200" width="200" height="200">
          </picture>
        </div>
      </div>
      <div>
      <span class="screen-readers">Texte fictif : </span><p>
  Fusce in pellentesque praesent est euismod elit eu pellentesque risus sed sit integer massa nonummy libero quam felis egestas cubilia amet blandit nunc ac felis pretium cursus integer mauris nec tempus vulputate fermentum pharetra non adipiscing nec.
  </p>
  <p>
  Eleifend bibendum justo adipiscing rhoncus curabitur placerat massa iaculis lectus fermentum orci sapien diam mauris consequat amet suspendisse in integer ornare ipsum quam vel ut massa cras pellentesque ultrices at nunc nibh.
  </p>
  </div></div>
  </details>
  <details class="plus-type outer-line" data-details-toggle="group-toggle">
    <summary class="display-block" id="summary_2_4">
      <span class="screen-readers">Texte fictif : </span>Lorem adipiscing proin ut
    </summary>
    <div aria-describedby="summary_2_4" class="padding-top-half-gutter flex flex-top half-gutter no-fit no-margin-bottom justify-content-stretch" data-nosnippet>
      <div class="xs-hide s-4 l-3">
        <div class="ratio-100">
          <picture class="dark-mode-hide">
            <img decoding="async" loading="lazy" src="https://pictures.kortic.com/200x200/000000.webp" alt="Image de remplacement 200x200" width="200" height="200">
          </picture>
          <picture class="dark-mode-show">
            <img decoding="async" loading="lazy" src="https://pictures.kortic.com/200x200/ffffff.webp" alt="Image de remplacement 200x200" width="200" height="200">
          </picture>
        </div>
      </div>
      <div>
      <span class="screen-readers">Texte fictif : </span><p>
  Nulla aliquam velit enim proin ligula blandit est sapien aliquam curae in sed molestie massa ultrices nibh iaculis massa nunc augue convallis a mi.
  </p>
  <p>
  Pulvinar duis convallis sed sed tincidunt nec nunc aliquam non ultrices nulla feugiat podo tristique convallis tortor in in mauris integer ultricies integer euismod magna rhoncus pharetra elementum eros aliquam vitae.
  </p>
  </div></div>
  </details>

mentors/templates/mentors/add_even.html
{% extends "base.html" %}

{% block main %}

{% endblock main %}

mentors/templates/mentors/add_forum.html
{% extends "base.html" %}

{% block main %}

{% endblock main %}

mentors/templates/mentors/add_ressource.html
{% extends "base.html" %}

{% block main %}

{% endblock main %}

mentors/templates/mentors/login.html
{% extends "base.html" %}

{% load static %}

{% block main %} 
					
<section class="vh-100 mt-3 mb-3" style="background-color: #eee;">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                <p class="text-center h6 fw-bold mb-5 mx-1 mx-md-4 mt-4">Connetez vous ou créez un compte <a href="{% url 'createuser' %}">ICI</a></p>
              <form method="post" action="{% url 'login_user' %}">
                {% csrf_token %}
                  <div class="form-floating mb-3">
                    <input type="text" name="username" class="form-control" id="floatingInput" required>
                    <label for="floatingInput">Nom utilisateur</label>
                  </div>
                  <div class="form-floating">
                    <input type="password" name="password" class="form-control" id="floatingPassword" required>
                    <label for="floatingPassword">Mot de passe</label>
                  </div>
                  <div class="p-t-20 mt-3">
                    <button class="btn btn-block btn-primary" type="submit">Inscrire</button>
                  </div>
              </form>

              </div>
              <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                  class="img-fluid" alt="Sample image">

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% for message in messages %}
        {% comment %} <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script> {% endcomment %}
        <script src="{% static 'js/sweetalert.min.js' %}"></script>
        {% if message.tags == 'error' %}
        <script>
            var m = "{{ message }}";
            swal("Réfusé!", m, "error");
        </script>
        {% elif message.tags == 'success' %}
        <script>
            var m = "{{ message }}";
            swal("Bienvenue!", m, "success");
        </script>
        {% elif message.tags == 'warning' %}
        <script>
            var m = "{{ message }}";
            swal("A bientôt!", m, "warning");
        </script>
        {% endif %}

    {% endfor%}

{% endblock main %}